name:          Code Guide
description:   Standards for developing flexible, durable, and sustainable HTML, CSS, and JavaScript.
url:           https://ravasthi.github.io/code-guide

markdown:      kramdown
permalink:     pretty
highlighter:   rouge

exclude:       ['config.ru', 'Gemfile', 'Gemfile.lock', 'Guardfile', 'LICENSE.md', 'README.md']

# baseurl:       http://code-guide.dev
# host:          code-guide.dev
